export const LOADING = "LOADING";
export const URL_GAMES = "https://ecomercestorebacken.vercel.app";
export const GET_ALL_GAMES = "GET_ALL_GAMES";
export const GET_BY_NAME_GAMES = "GET_BY_NAME_GAMES";
export const GET_BY_ID_GAMES = "GET_BY_ID_GAMES";
export const RESET_DETAIL_GAMES = "RESET_DETAIL_GAMES";
export const POST_VIDEOGAME = "POST_VIDEOGAME";
export const EDIT_VIDEOGAME = "EDIT_VIDEOGAME";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USERS_NOT_BANNED = "GET_USERS_NOT_BANNED";
export const GET_USERS_BANNED = "GET_USERS_BANNED";
export const BAN_USER = "BAN_USER";
export const UNBAN_USER = "UNBAN_USER";
export const UPDATE_USER = "UPDATE_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const FILTER_BY_ROL = "FILTER_BY_ROL";
export const GET_USER_BY_NAME = "GET_USER_BY_NAME";

export const AUTH_USER = "AUTH_USER";

export const GET_ALL_REVIEWS = "GET_REVIEWS";
export const GET_ENABLED_REVIEWS = "GET_ENABLED_REVIEWS";
export const GET_DELETED_REVIEWS = "GET_DELETED_REVIEWS";
export const GET_REVIEWS_OF_GAME = "GET_REVIEWS_OF_GAME";
export const GET_REVIEWS_OF_USER = "GET_REVIEWS_OF_USER";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const RESTORE_REVIEW = "RESTORE_REVIEW";

export const GET_ALL_BANNERS = "GET_ALL_BANNERS";
export const DELETE_BANNER = "DELETE_BANNER";
export const RESTORE_BANNER = "RESTORE_BANNER";
export const GET_DELETED_BANNERS = "GET_DELETED_BANNERS";
export const GET_ENABLED_BANNERS = "GET_ENABLED_BANNERS";

//!EDWARD
export const ORDER = "ORDER";
export const FILTER_PLATFORM = "FILTER_PLATFORM";
export const FILTER_DEVELOPER = "FILTER_DEVELOPER";
export const FILTER_GENRE = "FILTER_GENRE";
//!EDWARD


export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"

export const FETCH_REVIEWS_REQUEST = "FETCH_REVIEWS_REQUEST";
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAILURE = "FETCH_REVIEWS_FAILURE";