export const LOADING = "LOADING";
export const URL_GAMES = "https://ecomercestorebacken.vercel.app";

// VIDEOGAMES
export const GET_ALL_GAMES = "GET_ALL_GAMES";
export const GET_BY_NAME_GAMES = "GET_BY_NAME_GAMES";
export const GET_BY_ID_GAMES = "GET_BY_ID_GAMES";
export const RESET_DETAIL_GAMES = "RESET_DETAIL_GAMES";
export const POST_VIDEOGAME = "POST_VIDEOGAME";
export const EDIT_VIDEOGAME = "EDIT_VIDEOGAME";
export const DELETED_VIDEOGAMES = "DELETED_VIDEOGAMES";
export const GET_ACTIVE_VIDEOGAMES = "GET_ACTIVE_VIDEOGAMES";
export const DELETE_VIDEOGAME = "DELETE_VIDEOGAME";
export const RESTORE_VIDEOGAME = "RESTORE_VIDEOGAME";

// USERS
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USERS_NOT_BANNED = "GET_USERS_NOT_BANNED";
export const GET_USERS_BANNED = "GET_USERS_BANNED";
export const BAN_USER = "BAN_USER";
export const UNBAN_USER = "UNBAN_USER";
export const UPDATE_USER = "UPDATE_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const FILTER_BY_ROL = "FILTER_BY_ROL";
export const GET_USER_BY_NAME = "GET_USER_BY_NAME";
export const GET_USER_BY_EMAIL = "GET_USER_BY_EMAIL";
export const POST_USER = "POST_USER";
export const AUTH_USER = "AUTH_USER";

//!EDWARD
export const ORDER = "ORDER";
export const FILTER_PLATFORM = "FILTER_PLATFORM";
export const FILTER_DEVELOPER = "FILTER_DEVELOPER";
export const FILTER_GENRE = "FILTER_GENRE";
export const SET_SHOPPING_CART = "SET_SHOPPING_CART";
export const ADD_REJECTED_PURCHASE = 'ADD_REJECTED_PURCHASE';
export const ADD_SUCCESSFUL_PURCHASE = 'ADD_SUCCESSFUL_PURCHASE';
//!EDWARD

//❤Orders:
export const GET_ORDERS = "GET_ORDERS";
export const EDIT_ORDERS = "EDIT_ORDERS";
export const GET_BY_ID_ORDERS = "GET_BY_ID_ORDERS";
export const RESET_DETAIL_ORDERS = "RESET_DETAIL_ORDERS";
export const CANCELED_ORDER = "CANCELED_ORDER";
export const GET_ORDER_CANCELLED = "GET_ORDER_CANCELLED";
export const RESTORE_ORDER = "RESTORE_ORDER";
export const GET_ORDER_ACTIVE = "GET_ORDER_ACTIVE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
<<<<<<< HEAD
=======

//REVIEWS
export const GET_ALL_REVIEWS = "GET_REVIEWS";
export const GET_ENABLED_REVIEWS = "GET_ENABLED_REVIEWS";
export const GET_DELETED_REVIEWS = "GET_DELETED_REVIEWS";
export const GET_REVIEWS_OF_GAME = "GET_REVIEWS_OF_GAME";
export const GET_REVIEWS_OF_USER = "GET_REVIEWS_OF_USER";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const RESTORE_REVIEW = "RESTORE_REVIEW";
export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE';

//BANNERS
export const GET_ALL_BANNERS = "GET_ALL_BANNERS";
export const DELETE_BANNER = "DELETE_BANNER";
export const RESTORE_BANNER = "RESTORE_BANNER";
export const GET_DELETED_BANNERS = "GET_DELETED_BANNERS";
export const GET_ENABLED_BANNERS = "GET_ENABLED_BANNERS";
export const POST_BANNER_REQUEST = 'POST_BANNER_REQUEST';
export const POST_BANNER_SUCCESS = 'POST_BANNER_SUCCESS';
export const POST_BANNER_FAILURE = 'POST_BANNER_FAILURE';
>>>>>>> c656e8912fe7acca488a130d4c4fdc15b136f926
